name: Deploy Content to code116sentinelrg [714482ae-d9f3-42fb-bd50-ea9eeaf8a2c0]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-714482ae-d9f3-42fb-bd50-ea9eeaf8a2c0.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-714482ae-d9f3-42fb-bd50-ea9eeaf8a2c0.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'code116sentinelrg'
      workspaceName: 'code116sentinelrg'
      workspaceId: 'bb7e524e-cbd4-4ac6-b08a-d5ce2046926f'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,HuntingQuery,AutomationRule,Parser,Playbook,Workbook'
      branch: 'main'
      sourceControlId: '714482ae-d9f3-42fb-bd50-ea9eeaf8a2c0'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_714482aed9f342fbbd50ea9eeaf8a2c0 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-714482ae-d9f3-42fb-bd50-ea9eeaf8a2c0.ps1